---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: update system
    shell: apt update

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv']


  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: make workdir
    shell: mkdir /tmp/jenkins/

  - name: Copy docker file to server
    copy:
      src: /tmp/jenkins/workspace/pl1-ansible/Dockerfile
      dest: /tmp/jenkins/Dockerfile
      mode: '0644'

  - name: Copy sample.war to server
    copy:
      src: /tmp/jenkins/workspace/pl1-ansible/sample.war
      dest: /tmp/jenkins/sample.war
      mode: '0644'

  - name: build image
    shell:
      cmd: docker build -t tomcat_app -f ./Dockerfile .
      chdir: /tmp/jenkins/

  - name: create container
    shell: docker run --name container1 -d -p 8080:8080 tomcat_app  

